---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - iam.craft-conf.com
  resources:
  - serviceroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.craft-conf.com
  resources:
  - serviceroles/finalizers
  verbs:
  - update
- apiGroups:
  - iam.craft-conf.com
  resources:
  - serviceroles/status
  verbs:
  - get
  - patch
  - update
